config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resource :transactions do
  	get "balance"
  	get "atm"
  end
  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "transactions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :transactions

  after_initialize :default_values

  private
    def default_values
      self.balance ||= 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def update_account_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :balance)
	end

	def update_account_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :balance)
	end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all.order("created_at DESC")
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  def balance
    @transactions = Transaction.all.order("created_at DESC")
  end

  def atm
    @transaction = Transaction.new
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.amount > 0
        if @transaction.amount < current_user.balance
          if User.exists?(:id => @transaction.user_id)  
            if @transaction.user_id != current_user.id  
              if @transaction.save
                @current_user.update!(balance: @current_user.balance - @transaction.amount)
                @transaction.update!(from: @current_user.name, to: @transaction.user.name)
                @transaction.user.update!(balance: @transaction.user.balance + @transaction.amount)
      
                format.html { redirect_to root_path, notice: 'Transaction was successfully created.' }
                format.json { render :show, status: :created, location: @transaction }
              else
                format.html { render :new }
                format.json { render json: @transaction.errors, status: :unprocessable_entity }
              end
            else
            format.html { redirect_to new_transaction_path, alert: 'You cannot transfer money to yourself.' }
            end
          else
            format.html { redirect_to new_transaction_path, alert: 'The user account does not exist.' }
          end
        else
          format.html { redirect_to new_transaction_path, alert: 'The amount exceeds balance available in account.' }
        end
      else
        format.html { redirect_to new_transaction_path, alert: 'You cannot transfer a negative amount.' }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from, :to, :amount, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">The Ruby Bank</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>  

      <% if user_signed_in? %>
        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "button is-warning is-inverted" %>
              </p>
            </div>
          </div>
        </div>
      <% end %>

      <% if !user_signed_in? %>
        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'Login', new_user_session_path, class: "button is-warning is-inverted" %>
              </p>
            </div>
          </div>
        </div>
      <% end %>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/transactions/_accountInfo.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Account Information</p>
 
		<% if user_signed_in? %>

	      <div class="panel-block">
	      	<article class="media">
	      		<div class="media-content">
	      			<div class="content">
	      				<p><%= current_user.name %></p>
	      				<p>Balance: <%= current_user.balance %></p>
	      				<p>Account number: <%= current_user.id %> </p>
	      			</div>
	      		</div>
	      	</article>
	      </div>

		<% end %>
	</nav>


</div>

app/views/transactions/_actions.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <u> <%= link_to 'New Transaction', new_transaction_path, class: "a" %>  </u>
    <br/>
    <u> <%= link_to 'Balance History', :controller => 'transactions', :action=>'balance' %>  </u>
    <br/>
    <u> <%= link_to 'Visit ATM', :controller => 'transactions', :action=>'atm' %>  </u>
  </nav>
</div>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    
    <%= f.input :user_id, label: "To Account ID"%>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/_transactions.html.erb
<div class="column is-half">
	<article class="media-box">
		<figure class="media-left"></figure>
		<div class="media-content"></div>
	</article>

  <% @transactions.each do | transaction | %>
    <% if transaction.to == current_user.name || transaction.from == current_user.name %>
      <div class="box">
      	<article class="media">
      		<div class="media-left">
      			
      		</div>
      		<div class="media-content">
      			<div class="content">
      				<%= transaction.created_at.localtime.strftime("%d-%m-%y at %H:%M") %> <br/>

                    From: <strong><%= transaction.from %></strong><br/>
      				To: <strong><%= transaction.to %></strong><br/>
                    <% if transaction.to == current_user.name %>
      				  Amount: +<strong><%= transaction.amount %></strong><br/>
                    <% else %>
                      Amount: -<strong><%= transaction.amount %></strong><br/>
                    <% end %>

                      
                      <%= link_to transaction, method: :delete, data: { confirm: "Are you sure you want to delete this transaction?" } do %>
                          <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                      <% end %>
      			</div>
      		</div>
      	</article>
      </div>
    <% end %>
  <% end %>

</div>

app/views/transactions/atm.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="column is-half">
	    <div class="box">
          	<article class="media">
          		<div class="media-content">
          			<div class="content">
          				<%= f.input :amount, label: "How much money are you going to put on your account: " %>
				</div>
          		</div>
          	</article>
          </div>
    </div>
<%end%>

app/views/transactions/balance.html.erb
<div class="column is-half">
<% ledger = current_user.balance %>

  <% @transactions.each do | transaction | %>
    
    <% if transaction.to == current_user.name %>
      <div class="box">
      	<article class="media">
      		<div class="media-content">
      			<div class="content">
      				<%= transaction.created_at.localtime.strftime("%d-%m-%y at %H:%M") %> <br/>
					New Balance: <strong><%= ledger %> </strong> <br/> 
                    
					Added amount: +<strong><%= transaction.amount %></strong><br/>
					Old Balance: <%= ledger -= transaction.amount %> <br/>
				</div>
      		</div>
      	</article>
      </div>
    <% end %>

    <% if transaction.from == current_user.name %> 
      <div class="box">
      	<article class="media">
      		<div class="media-content">
      			<div class="content">
      				<%= transaction.created_at.localtime.strftime("%d-%m-%y at %H:%M") %> <br/>
					New Balance: <strong><%= ledger %> </strong> <br/> 
                    
					Subtracted amount: -<strong><%= transaction.amount %></strong><br/>
					Old Balance: <%= ledger += transaction.amount %> <br/>
				</div>                 
                      

      		</div>
      	</article>
      </div>
    <% end %>
  <% end %>

  <% if ledger > 0 %>
  <div class="box">
      	<article class="media">
      		<div class="media-content">
      			<div class="content">                    
					Initial Deposit: <strong><%= ledger %> </strong> <br/> 
				</div>                  
      		</div>
      	</article>
      </div>
    <% end %>

</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'actions' %>
      <%= render 'transactions' %>
      <%= render 'accountInfo' %>
    </div>
  </div>
</section>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @transaction.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @transaction.to %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>ID:</strong>
  <%= @transaction.id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>